version: '3'
services:
   mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/db
    
   springboot-app:
    build: .
    ports:
    - 8085:8085
   
    depends_on:
    - mysql
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/student-management
    
      
      
volumes:
  mongo-data: